version: '3.8'

services:
    web:
        image: sentiport-heroku_web:topic-extraction-packed
        build: .
        command: gunicorn --bind :8000 sentiport:app --reload # DEBUG
        volumes:
          - ./sentiport:/sentiport
          - ./sentiport/static:/sentiport/static
        env_file:
          - .env 
        ports:
          - 8000:8000
