version: '3.8'

services:
    web:
        build: .
        command: gunicorn --bind :8000 sentiport:app --reload # DEBUG
        volumes:
          - ./sentiport:/sentiport
          - ./sentiport/static:/sentiport/static
        env_file:
          - .env 
        ports:
          - 8000:8000

    redis:
      image: "redis:alpine"
